# Generated by Django 4.2.16 on 2025-10-23 23:55

from decimal import Decimal
from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livro_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RemoveField(
            model_name='livro',
            name='capa',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Empréstimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leitor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='leitor',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taxa'),
        ),
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Publicação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
    ]
