# Generated by Django 4.2.16 on 2025-11-02 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emprestimo_options_remove_livro_capa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_agendada'], 'verbose_name': 'Agendamento de Retirada', 'verbose_name_plural': 'Agendamentos de Retirada'},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_agendada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Agendada'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_retirada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Retirada'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Empréstimo'),
        ),
    ]
