# Generated by Django 4.2.16 on 2025-11-02 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_agendamento_options_alter_emprestimo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendada',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data Agendada'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Empréstimo'),
        ),
    ]
